server:
  port: 20089
eureka:
  instance:
    hostname: localhost
  client:
    # Via register-with-eureka and fetch-registry value false to claim a server
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false